select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_float_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_double_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table80_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(distinct `col_float_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`pk`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_char_20`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned`, tmp.`pk` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_float_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_char_20_key`) as a from (select * from `table60_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_varchar_20_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_decimal_6_3_signed` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_varchar_20`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_float_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_varchar_20_key`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_bigint_unsigned` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_bigint_signed`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_float_signed` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_bigint_signed` order by a;
select count(`pk`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_char_20_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`pk`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_float_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_varchar_20` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_double_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_char_20`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_bigint_unsigned` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_char_20_key`, tmp.`col_bigint_signed_key` order by a;
select count(`col_double_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_varchar_20`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_bigint_unsigned_key` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_float_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_float_signed` order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `pk`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_signed_key` order by a;
select count(`col_bigint_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_varchar_20` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_char_20_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key`, tmp.`col_char_20` order by a;
select count(distinct `col_char_20`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_double_signed` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_char_20`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `pk`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_double_signed` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key`, tmp.`col_bigint_unsigned_key` order by a;
select count(`pk`) as a from (select * from `table70_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `pk`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_varchar_20_key`, tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_char_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `col_varchar_20_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_double_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_float_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_bigint_signed_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(`col_decimal_40_20_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_char_20` order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(`col_varchar_20`) as a from (select * from `table30_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_float_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_signed_key`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_float_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_double_signed` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_double_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed`, tmp.`col_float_signed` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_double_signed` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_varchar_20_key` order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key`, tmp.`col_char_20` order by a;
select count(`col_float_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_decimal_6_3_signed` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_bigint_unsigned`, tmp.`pk` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_char_20`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key`, tmp.`col_double_signed_key` order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `pk`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(`col_double_signed_key`) as a from (select * from `table70_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_char_20_key`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(`col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_char_20`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key`, tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(`pk`) as a from (select * from `table30_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key`, tmp.`col_bigint_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_char_20`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_double_signed` order by a;
select count(distinct `pk`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(`col_double_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_10_4_signed` order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_signed`, tmp.`col_char_20_key` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_bigint_unsigned`, tmp.`pk` order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table60_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_varchar_20_key` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table30_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_float_unsigned` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20_key`, tmp.`col_varchar_20` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_float_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key`, tmp.`col_double_unsigned` order by a;
select count(`col_decimal_40_20_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_signed`, tmp.`col_double_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_float_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_char_20_key`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_char_20_key`) as a from (select * from `table60_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_double_signed_key` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_char_20_key`) as a from (select * from `table70_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`pk`, tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_float_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_char_20_key`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_varchar_20`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_char_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_varchar_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_double_unsigned` order by a;
select count(`col_float_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_float_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `pk`) as a from (select * from `table80_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_varchar_20`) as a from (select * from `table40_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key`, tmp.`col_decimal_6_3_signed` order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_varchar_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key`, tmp.`col_float_signed_key` order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key`, tmp.`col_varchar_20_key` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_double_signed_key`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_bigint_signed` order by a;
select count(`col_float_signed_key`) as a from (select * from `table70_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_float_signed` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_double_signed_key`) as a from (select * from `table70_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_signed` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned` order by a;
select count(`col_bigint_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_float_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_10_4_signed` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(`col_decimal_40_20_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned`, tmp.`col_double_unsigned_key` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_varchar_20_key`) as a from (select * from `table30_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(`col_bigint_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_bigint_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_char_20` order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_double_signed_key` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_signed_key` order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_unsigned`, tmp.`col_varchar_20_key` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_signed_key`, tmp.`col_decimal_40_20_signed` order by a;
select count(`col_bigint_signed`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(distinct `pk`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(`col_double_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_decimal_40_20_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_char_20_key`, tmp.`col_double_unsigned_key` order by a;
select count(`col_char_20`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`pk` order by a;
select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_decimal_6_3_signed` order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(`col_char_20`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_char_20`, tmp.`col_float_unsigned_key` order by a;
select count(distinct `pk`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_bigint_signed` order by a;
select count(distinct `col_float_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_float_signed` order by a;
select count(`col_float_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_signed`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(`col_char_20_key`) as a from (select * from `table10_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_signed_key` order by a;
select count(`col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(`col_float_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_float_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `pk`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed`, tmp.`col_varchar_20` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_float_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_signed_key`, tmp.`col_decimal_6_3_signed` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_double_signed` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_varchar_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_signed`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_char_20_key`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table60_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table60_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_bigint_unsigned_key` order by a;
select count(`pk`) as a from (select * from `table30_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_unsigned_key`, tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_bigint_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_double_signed_key`, tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_decimal_10_4_signed` order by a;
select count(`col_float_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_varchar_20_key`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_decimal_6_3_signed` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_float_unsigned` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_char_20` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_bigint_signed` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_float_signed_key` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_bigint_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_varchar_20_key`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_decimal_6_3_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key`, tmp.`col_char_20` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_float_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(distinct `col_double_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_bigint_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key`, tmp.`col_bigint_signed_key` order by a;
select count(distinct `col_char_20_key`) as a from (select * from `table80_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`pk`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_float_signed` order by a;
select count(`col_char_20_key`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`pk` order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_double_signed` order by a;
select count(`pk`) as a from (select * from `table90_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_float_signed_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_bigint_unsigned` order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table40_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `pk`) as a from (select * from `table20_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_varchar_20`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_float_unsigned_key` order by a;
select count(`pk`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`pk`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_float_unsigned` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_bigint_unsigned` order by a;
select count(`col_bigint_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_char_20` order by a;
select count(`col_float_signed`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_unsigned`, tmp.`pk` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_unsigned` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_bigint_unsigned` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(`col_char_20`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table70_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `pk`) as a from (select * from `table60_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_double_signed` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`col_double_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed`, tmp.`col_varchar_20_key` order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed`, tmp.`col_decimal_40_20_unsigned` order by a;
select count(distinct `col_char_20_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(distinct `col_char_20`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned`, tmp.`col_varchar_20_key` order by a;
select count(`col_decimal_40_20_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_float_unsigned_key` order by a;
select count(`col_char_20`) as a from (select * from `table10_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_float_signed` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table50_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned` order by a;
select count(`col_char_20_key`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key`, tmp.`col_float_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_char_20_key`, tmp.`col_double_unsigned` order by a;
select count(`col_char_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed` order by a;
select count(`col_float_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_varchar_20`, tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(`pk`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`pk` order by a;
select count(distinct `pk`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table50_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_float_signed` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_double_unsigned` order by a;
select count(distinct `col_bigint_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_double_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_bigint_signed_key`, tmp.`col_double_unsigned` order by a;
select count(`col_double_unsigned`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_varchar_20` order by a;
select count(distinct `pk`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(`col_decimal_40_20_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table40_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from (select * from `table10_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(`col_varchar_20_key`) as a from (select * from `table50_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table20_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_varchar_20_key` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_double_unsigned_key` order by a;
select count(`col_decimal_6_3_signed`) as a from (select * from `table30_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_char_20`, tmp.`col_char_20` order by a;
select count(`col_float_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_double_signed_key`, tmp.`col_decimal_10_4_signed_key` order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_char_20` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed` order by a;
select count(`col_double_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table90_int_autoinc`) tmp order by a;
select count(`col_double_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_varchar_20_key` order by a;
select count(`col_float_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from (select * from `table70_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_decimal_6_3_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from (select * from `table30_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table80_int_autoinc`) tmp order by a;
select count(`col_bigint_unsigned_key`) as a from (select * from `table30_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table20_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table70_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_signed_key`, tmp.`col_double_unsigned_key` order by a;
select count(distinct `col_double_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_double_signed`, tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(`col_decimal_6_3_unsigned`) as a from (select * from `table20_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_char_20`) as a from (select * from `table10_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_double_unsigned`, tmp.`col_decimal_10_4_unsigned` order by a;
select count(`col_double_unsigned`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_float_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(`col_float_signed`) as a from (select * from `table20_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_char_20_key` order by a;
select count(distinct `col_float_unsigned_key`) as a from (select * from `table80_int_autoinc` union all select * from `table40_int_autoinc`) tmp group by tmp.`col_decimal_6_3_unsigned_key`, tmp.`col_float_signed` order by a;
select count(`col_decimal_10_4_unsigned`) as a from (select * from `table10_int_autoinc` union all select * from `table60_int_autoinc`) tmp group by tmp.`col_float_unsigned`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_bigint_unsigned`) as a from (select * from `table90_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_decimal_6_3_signed_key` order by a;
select count(distinct `col_double_unsigned_key`) as a from (select * from `table90_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table50_int_autoinc` union all select * from `table10_int_autoinc`) tmp order by a;
select count(distinct `col_char_20`) as a from (select * from `table90_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table20_int_autoinc`) tmp order by a;
select count(`col_float_signed_key`) as a from (select * from `table30_int_autoinc` union all select * from `table80_int_autoinc`) tmp group by tmp.`col_bigint_unsigned_key`, tmp.`col_decimal_10_4_signed` order by a;
select count(distinct `col_float_unsigned`) as a from (select * from `table50_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_float_signed_key` order by a;
select count(`col_char_20_key`) as a from (select * from `table70_int_autoinc` union all select * from `table30_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from (select * from `table60_int_autoinc` union all select * from `table30_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_char_20_key` order by a;
select count(`col_varchar_20`) as a from (select * from `table20_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_float_signed` order by a;
select count(`col_varchar_20`) as a from (select * from `table60_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_decimal_40_20_signed`, tmp.`col_decimal_6_3_unsigned` order by a;
select count(`col_double_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_varchar_20`) as a from (select * from `table20_int_autoinc` union all select * from `table60_int_autoinc`) tmp order by a;
select count(`col_decimal_10_4_signed_key`) as a from (select * from `table10_int_autoinc` union all select * from `table70_int_autoinc`) tmp order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from (select * from `table90_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_10_4_signed_key`, tmp.`col_decimal_40_20_signed` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from (select * from `table60_int_autoinc` union all select * from `table40_int_autoinc`) tmp order by a;
select count(distinct `col_bigint_signed`) as a from (select * from `table50_int_autoinc` union all select * from `table70_int_autoinc`) tmp group by tmp.`col_float_unsigned_key`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from (select * from `table80_int_autoinc` union all select * from `table90_int_autoinc`) tmp group by tmp.`col_decimal_40_20_unsigned_key`, tmp.`col_bigint_signed` order by a;
select count(distinct `pk`) as a from (select * from `table60_int_autoinc` union all select * from `table50_int_autoinc`) tmp group by tmp.`col_bigint_unsigned`, tmp.`col_decimal_40_20_signed_key` order by a;
select count(distinct `col_float_signed_key`) as a from (select * from `table40_int_autoinc` union all select * from `table10_int_autoinc`) tmp group by tmp.`col_decimal_10_4_unsigned_key` order by a;
