# 14:28:24 Default schema: test
# 14:28:24 Caching metadata for dbi:mysql:host=127.0.0.1:port=4000:user=root:password=:database=test
select count(distinct `col_decimal_6_3_signed`) as a from `table40_int_autoinc` group by `col_decimal_6_3_signed`, `col_bigint_unsigned` order by a;
select count(`col_float_signed`) as a from `table20_int_autoinc` order by a;
select count(distinct `col_varchar_20_key`) as a from `table20_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from `table60_int_autoinc` group by `col_char_20` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from `table20_int_autoinc` group by `col_char_20_key`, `col_varchar_20` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table70_int_autoinc` order by a;
select a, count(b) as b from (select `col_double_signed` as a, `col_double_signed_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_signed`) as a from `table10_int_autoinc` order by a;
select a, count(distinct b) as b from (select `pk` as a, `col_decimal_6_3_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from `table60_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_6_3_unsigned` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from `table60_int_autoinc` group by `col_char_20_key` order by a;
select a, count(b) as b from (select `col_decimal_6_3_unsigned` as a, `pk` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table40_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select a, count(b) as b from (select `col_varchar_20_key` as a, `col_float_unsigned_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_signed_key`) as a from `table80_int_autoinc` group by `col_char_20_key` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from `table20_int_autoinc` order by a;
select count(`col_float_signed`) as a from `table20_int_autoinc` group by `col_float_signed_key`, `col_varchar_20_key` order by a;
select a, count(b) as b from (select `col_char_20` as a, `col_decimal_40_20_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_float_signed_key`) as a from `table10_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(`col_double_unsigned`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table90_int_autoinc` group by `col_double_signed_key` order by a;
select count(`col_char_20`) as a from `table40_int_autoinc` order by a;
select count(`pk`) as a from `table40_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_10_4_signed` as a, `col_decimal_40_20_signed_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_signed_key`) as a from `table80_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_double_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_float_signed`) as a from `table70_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_float_signed`) as a from `table90_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_unsigned_key` as a, `col_bigint_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `col_bigint_unsigned_key` as a, `col_decimal_40_20_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_decimal_6_3_unsigned_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_unsigned_key`) as a from `table70_int_autoinc` order by a;
select count(`col_bigint_signed`) as a from `table80_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table60_int_autoinc` group by `col_double_signed`, `col_float_signed` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table90_int_autoinc` group by `col_decimal_10_4_signed` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table40_int_autoinc` group by `col_float_signed`, `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_char_20`) as a from `table80_int_autoinc` group by `pk` order by a;
select count(`col_char_20_key`) as a from `table20_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_signed` as a, `col_double_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_varchar_20_key`) as a from `table30_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_unsigned` as a, `col_decimal_10_4_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_char_20`) as a from `table80_int_autoinc` group by `col_varchar_20` order by a;
select count(`col_double_signed`) as a from `table20_int_autoinc` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table70_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_double_signed` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table10_int_autoinc` order by a;
select a, count(b) as b from (select `col_char_20_key` as a, `col_decimal_10_4_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_signed`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table20_int_autoinc` order by a;
select count(`col_double_unsigned`) as a from `table90_int_autoinc` group by `col_decimal_6_3_unsigned_key` order by a;
select a, count(distinct b) as b from (select `col_char_20_key` as a, `col_bigint_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_signed_key`) as a from `table40_int_autoinc` group by `col_double_signed`, `col_bigint_unsigned` order by a;
select count(`col_double_signed_key`) as a from `table50_int_autoinc` group by `col_char_20`, `col_double_signed` order by a;
select a, count(b) as b from (select `pk` as a, `col_bigint_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_unsigned_key`) as a from `table70_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table40_int_autoinc` group by `col_bigint_unsigned`, `col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table40_int_autoinc` group by `col_bigint_signed` order by a;
select count(distinct `pk`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from `table70_int_autoinc` group by `pk`, `col_decimal_40_20_unsigned` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_signed` as a, `col_bigint_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_float_signed_key`) as a from `table50_int_autoinc` order by a;
select count(`col_varchar_20`) as a from `table50_int_autoinc` group by `col_char_20`, `col_decimal_6_3_signed` order by a;
select a, count(b) as b from (select `pk` as a, `col_char_20_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `col_decimal_10_4_signed_key` as a, `col_varchar_20` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_char_20_key`) as a from `table40_int_autoinc` group by `col_decimal_6_3_unsigned_key` order by a;
select count(`col_double_signed`) as a from `table90_int_autoinc` group by `col_decimal_40_20_signed` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table30_int_autoinc` group by `col_decimal_10_4_signed` order by a;
select a, count(distinct b) as b from (select `col_bigint_signed_key` as a, `col_decimal_40_20_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `col_decimal_10_4_unsigned_key` as a, `col_char_20` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_decimal_40_20_signed` as a, `col_char_20_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_char_20_key`) as a from `table80_int_autoinc` group by `col_decimal_40_20_unsigned`, `col_float_signed` order by a;
select count(`col_double_signed`) as a from `table50_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table70_int_autoinc` group by `col_float_signed_key`, `col_decimal_10_4_unsigned` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_signed` as a, `col_decimal_6_3_unsigned_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_signed`) as a from `table90_int_autoinc` order by a;
select count(`col_char_20_key`) as a from `table10_int_autoinc` group by `col_float_signed`, `col_bigint_unsigned_key` order by a;
select count(distinct `col_double_signed`) as a from `table40_int_autoinc` group by `col_char_20`, `col_char_20` order by a;
select count(`col_bigint_unsigned_key`) as a from `table20_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table80_int_autoinc` group by `pk`, `col_bigint_unsigned` order by a;
select count(`col_double_signed`) as a from `table40_int_autoinc` group by `col_float_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table10_int_autoinc` order by a;
select count(distinct `col_varchar_20_key`) as a from `table30_int_autoinc` group by `col_float_signed_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table60_int_autoinc` group by `col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from `table40_int_autoinc` group by `col_bigint_unsigned_key`, `col_bigint_unsigned_key` order by a;
select count(`col_float_signed_key`) as a from `table50_int_autoinc` group by `col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from `table40_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from `table20_int_autoinc` group by `col_float_signed_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from `table70_int_autoinc` group by `pk`, `col_bigint_signed_key` order by a;
select count(distinct `col_varchar_20_key`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_float_signed_key`) as a from `table40_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_unsigned` as a, `col_bigint_unsigned_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_unsigned_key`) as a from `table80_int_autoinc` group by `col_varchar_20`, `col_char_20` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table40_int_autoinc` order by a;
select count(`col_float_signed_key`) as a from `table20_int_autoinc` order by a;
select count(`col_float_unsigned_key`) as a from `table80_int_autoinc` group by `pk`, `col_double_unsigned_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table80_int_autoinc` group by `col_decimal_6_3_unsigned` order by a;
select count(distinct `col_decimal_40_20_signed_key`) as a from `table50_int_autoinc` group by `col_decimal_6_3_signed_key`, `col_decimal_10_4_signed_key` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table50_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table50_int_autoinc` group by `col_decimal_6_3_signed` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from `table90_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table90_int_autoinc` group by `col_char_20` order by a;
select count(`col_float_signed`) as a from `table60_int_autoinc` group by `col_decimal_40_20_signed`, `col_decimal_6_3_signed_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table60_int_autoinc` order by a;
select count(`col_decimal_40_20_signed_key`) as a from `table50_int_autoinc` group by `col_char_20` order by a;
select count(`col_varchar_20`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_bigint_unsigned`) as a from `table80_int_autoinc` group by `col_bigint_unsigned_key` order by a;
select a, count(b) as b from (select `col_char_20_key` as a, `col_double_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_40_20_unsigned`) as a from `table70_int_autoinc` order by a;
select count(distinct `col_char_20`) as a from `table10_int_autoinc` order by a;
select count(`col_float_signed_key`) as a from `table20_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_double_signed`) as a from `table60_int_autoinc` order by a;
select count(`col_float_signed`) as a from `table20_int_autoinc` group by `col_float_signed_key`, `col_varchar_20_key` order by a;
select count(`col_bigint_signed`) as a from `table90_int_autoinc` group by `col_varchar_20`, `col_decimal_10_4_signed_key` order by a;
select count(distinct `col_bigint_signed`) as a from `table50_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table50_int_autoinc` group by `col_float_signed` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table40_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_char_20_key` as a, `col_bigint_signed` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_decimal_6_3_unsigned` as a, `col_decimal_10_4_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_bigint_unsigned`) as a from `table50_int_autoinc` group by `col_bigint_signed_key` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table50_int_autoinc` group by `col_decimal_40_20_signed`, `col_decimal_40_20_signed` order by a;
select count(distinct `col_decimal_6_3_signed`) as a from `table40_int_autoinc` order by a;
select count(`col_float_unsigned_key`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned_key`, `col_decimal_10_4_signed_key` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table20_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_unsigned` as a, `col_decimal_6_3_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_signed`) as a from `table60_int_autoinc` group by `col_decimal_10_4_signed`, `col_bigint_unsigned` order by a;
select count(`col_char_20_key`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table90_int_autoinc` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table20_int_autoinc` order by a;
select count(`col_bigint_signed_key`) as a from `table80_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table40_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_40_20_signed_key` as a, `col_bigint_unsigned` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_signed_key`) as a from `table70_int_autoinc` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table90_int_autoinc` order by a;
select count(`col_decimal_40_20_signed_key`) as a from `table30_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(distinct `col_varchar_20`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table10_int_autoinc` group by `col_bigint_unsigned_key`, `col_bigint_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from `table60_int_autoinc` order by a;
select count(`col_bigint_signed`) as a from `table20_int_autoinc` order by a;
select count(`col_double_unsigned`) as a from `table80_int_autoinc` group by `pk`, `col_bigint_signed_key` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from `table90_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table10_int_autoinc` group by `pk` order by a;
select count(`col_float_unsigned`) as a from `table70_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_bigint_unsigned` order by a;
select a, count(distinct b) as b from (select `col_bigint_unsigned` as a, `col_decimal_40_20_signed` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_signed`) as a from `table60_int_autoinc` group by `col_char_20_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table60_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(`col_double_unsigned`) as a from `table60_int_autoinc` group by `col_bigint_unsigned_key` order by a;
select a, count(b) as b from (select `col_decimal_40_20_signed` as a, `col_float_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_unsigned`) as a from `table40_int_autoinc` order by a;
select count(`col_char_20`) as a from `table40_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_unsigned` as a, `col_varchar_20` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_10_4_signed`) as a from `table10_int_autoinc` group by `col_bigint_unsigned_key`, `col_bigint_signed` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table70_int_autoinc` group by `col_double_signed` order by a;
select count(distinct `pk`) as a from `table50_int_autoinc` order by a;
select count(`col_decimal_10_4_signed`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from `table30_int_autoinc` group by `col_decimal_6_3_unsigned_key` order by a;
select a, count(b) as b from (select `col_decimal_40_20_signed` as a, `col_decimal_6_3_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_varchar_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`pk`) as a from `table90_int_autoinc` group by `col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table20_int_autoinc` order by a;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_bigint_signed_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_varchar_20`) as a from `table10_int_autoinc` group by `col_decimal_10_4_signed` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_double_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table70_int_autoinc` group by `col_decimal_6_3_signed` order by a;
select a, count(b) as b from (select `col_varchar_20` as a, `col_float_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table50_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_signed` as a, `col_bigint_signed` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_varchar_20`) as a from `table90_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select a, count(b) as b from (select `col_varchar_20` as a, `col_char_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_signed_key`) as a from `table20_int_autoinc` order by a;
select count(`col_decimal_6_3_signed_key`) as a from `table60_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_float_signed`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_varchar_20_key`) as a from `table90_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table50_int_autoinc` order by a;
select count(distinct `col_double_signed_key`) as a from `table90_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_signed` as a, `col_float_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_unsigned`) as a from `table10_int_autoinc` order by a;
select a, count(distinct b) as b from (select `pk` as a, `col_decimal_40_20_unsigned_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_bigint_signed` as a, `col_double_signed_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_bigint_unsigned_key`) as a from `table80_int_autoinc` group by `pk`, `col_char_20_key` order by a;
select count(distinct `col_bigint_signed_key`) as a from `table60_int_autoinc` group by `col_char_20_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_signed_key` as a, `col_double_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_bigint_unsigned_key`) as a from `table80_int_autoinc` group by `col_float_signed_key` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from `table10_int_autoinc` group by `col_float_signed_key`, `col_char_20_key` order by a;
select count(`col_decimal_40_20_signed`) as a from `table70_int_autoinc` group by `col_float_signed`, `col_double_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_char_20_key`) as a from `table70_int_autoinc` group by `col_varchar_20_key`, `col_float_signed_key` order by a;
select count(distinct `pk`) as a from `table10_int_autoinc` group by `pk` order by a;
select count(distinct `col_double_signed`) as a from `table20_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a;
select count(`pk`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_float_signed`) as a from `table60_int_autoinc` order by a;
select count(`col_float_unsigned_key`) as a from `table40_int_autoinc` group by `col_decimal_6_3_unsigned` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_signed` as a, `col_decimal_40_20_unsigned` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table60_int_autoinc` group by `col_varchar_20` order by a;
select count(distinct `col_double_signed_key`) as a from `table20_int_autoinc` order by a;
select count(distinct `col_double_signed`) as a from `table90_int_autoinc` order by a;
select count(`col_char_20`) as a from `table60_int_autoinc` group by `col_varchar_20_key` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from `table10_int_autoinc` group by `col_varchar_20_key`, `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_double_signed_key`) as a from `table80_int_autoinc` group by `col_decimal_40_20_signed`, `col_float_signed` order by a;
select count(`col_double_unsigned`) as a from `table40_int_autoinc` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table20_int_autoinc` group by `col_float_signed_key`, `col_decimal_6_3_unsigned_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_unsigned` as a, `col_decimal_10_4_signed` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_double_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_varchar_20_key` as a, `col_decimal_6_3_signed_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_double_signed`) as a from `table80_int_autoinc` group by `col_bigint_unsigned`, `col_decimal_6_3_signed_key` order by a;
select count(`col_decimal_6_3_signed`) as a from `table50_int_autoinc` group by `col_bigint_signed_key`, `col_bigint_signed_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table20_int_autoinc` group by `col_decimal_10_4_signed` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table90_int_autoinc` group by `col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table20_int_autoinc` order by a;
select count(`col_double_signed`) as a from `table70_int_autoinc` group by `col_decimal_40_20_signed_key`, `col_bigint_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from `table60_int_autoinc` order by a;
select count(`col_float_unsigned_key`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_double_signed` order by a;
select a, count(b) as b from (select `col_double_signed` as a, `col_double_unsigned` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_unsigned_key`) as a from `table60_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_double_signed`) as a from `table70_int_autoinc` group by `col_varchar_20`, `col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_40_20_signed_key`) as a from `table90_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_decimal_10_4_unsigned_key` order by a;
select count(`col_double_unsigned`) as a from `table30_int_autoinc` group by `col_decimal_6_3_unsigned` order by a;
select count(`col_double_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_bigint_unsigned`) as a from `table50_int_autoinc` order by a;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_double_signed_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_40_20_unsigned_key`) as a from `table50_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_bigint_signed` as a, `col_decimal_6_3_unsigned` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_char_20`) as a from `table50_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_char_20` order by a;
select count(`col_decimal_10_4_unsigned`) as a from `table80_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_varchar_20`) as a from `table40_int_autoinc` group by `col_decimal_40_20_signed` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from `table40_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_10_4_signed_key` as a, `col_bigint_signed_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_decimal_10_4_signed_key` as a, `pk` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_float_signed`) as a from `table60_int_autoinc` group by `col_char_20`, `col_double_signed_key` order by a;
select count(`col_float_signed`) as a from `table70_int_autoinc` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from `table40_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_char_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_unsigned_key`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from `table40_int_autoinc` group by `col_bigint_signed_key`, `col_bigint_unsigned` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_bigint_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_double_signed_key` as a, `col_double_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_bigint_unsigned`) as a from `table40_int_autoinc` group by `col_float_signed`, `col_decimal_40_20_signed_key` order by a;
select count(`col_double_signed`) as a from `table10_int_autoinc` order by a;
select count(distinct `col_float_signed`) as a from `table80_int_autoinc` group by `col_bigint_signed` order by a;
select count(`col_double_signed_key`) as a from `table70_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table40_int_autoinc` order by a;
select count(`col_double_unsigned_key`) as a from `table30_int_autoinc` group by `col_decimal_6_3_unsigned`, `col_decimal_40_20_signed` order by a;
select a, count(b) as b from (select `col_double_signed_key` as a, `col_decimal_6_3_signed_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `col_bigint_signed_key` as a, `col_bigint_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `pk` as a, `col_float_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_6_3_signed`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from `table90_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_signed`) as a from `table10_int_autoinc` group by `col_decimal_6_3_signed_key`, `col_decimal_6_3_signed` order by a;
select count(`col_decimal_6_3_signed_key`) as a from `table30_int_autoinc` order by a;
select count(`col_decimal_40_20_signed`) as a from `table90_int_autoinc` group by `col_varchar_20_key` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_6_3_signed`, `col_double_signed_key` order by a;
select count(`col_bigint_unsigned_key`) as a from `table20_int_autoinc` group by `col_char_20_key`, `col_decimal_40_20_unsigned` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned_key` as a, `pk` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `col_bigint_signed_key` as a, `col_decimal_6_3_unsigned` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table70_int_autoinc` group by `col_bigint_signed` order by a;
select count(distinct `col_bigint_signed_key`) as a from `table90_int_autoinc` group by `col_varchar_20_key`, `col_bigint_signed_key` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned` as a, `col_float_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_6_3_signed_key`) as a from `table90_int_autoinc` group by `col_char_20` order by a;
select a, count(b) as b from (select `col_decimal_6_3_unsigned_key` as a, `col_varchar_20` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_varchar_20`) as a from `table50_int_autoinc` group by `col_decimal_6_3_signed_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table90_int_autoinc` group by `col_decimal_6_3_signed_key`, `col_decimal_40_20_unsigned_key` order by a;
select count(`col_char_20`) as a from `table40_int_autoinc` group by `col_bigint_signed_key`, `col_float_signed_key` order by a;
select count(`col_double_signed`) as a from `table40_int_autoinc` order by a;
select count(`col_bigint_unsigned_key`) as a from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_double_signed`) as a from `table80_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_varchar_20_key` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table80_int_autoinc` order by a;
select count(`col_decimal_40_20_unsigned_key`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table90_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_decimal_40_20_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_unsigned_key`) as a from `table60_int_autoinc` order by a;
select a, count(b) as b from (select `col_bigint_unsigned_key` as a, `col_decimal_40_20_signed_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_float_signed`) as a from `table60_int_autoinc` group by `col_decimal_40_20_signed`, `col_float_signed_key` order by a;
select count(distinct `col_float_unsigned`) as a from `table30_int_autoinc` group by `col_char_20_key`, `col_double_signed_key` order by a;
select count(`col_float_unsigned`) as a from `table20_int_autoinc` group by `col_double_signed` order by a;
select a, count(distinct b) as b from (select `col_varchar_20` as a, `col_decimal_10_4_unsigned` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_10_4_signed`) as a from `table80_int_autoinc` group by `col_bigint_signed`, `col_bigint_signed_key` order by a;
select count(distinct `col_bigint_signed`) as a from `table80_int_autoinc` group by `col_bigint_unsigned_key`, `col_float_signed` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table50_int_autoinc` order by a;
select count(distinct `col_char_20`) as a from `table60_int_autoinc` group by `col_decimal_6_3_signed_key`, `col_decimal_40_20_unsigned` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_signed_key` as a, `col_decimal_10_4_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_float_unsigned_key`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_varchar_20_key`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_varchar_20_key`) as a from `table70_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_double_signed_key` order by a;
select count(`col_float_signed`) as a from `table50_int_autoinc` group by `col_decimal_6_3_signed` order by a;
select count(distinct `col_char_20`) as a from `table90_int_autoinc` group by `col_double_signed_key`, `col_decimal_40_20_unsigned` order by a;
select count(`col_float_signed`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_char_20_key`) as a from `table30_int_autoinc` group by `col_float_signed`, `col_varchar_20` order by a;
select a, count(distinct b) as b from (select `col_char_20` as a, `col_decimal_6_3_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_bigint_signed_key`) as a from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_signed` as a, `col_decimal_40_20_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_bigint_signed`) as a from `table40_int_autoinc` order by a;
select count(`col_char_20`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_double_signed`) as a from `table40_int_autoinc` group by `col_float_signed`, `col_double_signed_key` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table60_int_autoinc` group by `col_decimal_6_3_signed_key` order by a;
select count(`col_float_signed`) as a from `table60_int_autoinc` group by `col_float_signed`, `col_decimal_40_20_signed` order by a;
select count(distinct `col_char_20`) as a from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table60_int_autoinc` group by `col_varchar_20` order by a;
select count(`pk`) as a from `table20_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_40_20_signed` order by a;
select a, count(distinct b) as b from (select `col_varchar_20` as a, `col_decimal_6_3_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_10_4_signed_key`) as a from `table30_int_autoinc` group by `col_decimal_10_4_signed`, `col_decimal_10_4_signed_key` order by a;
select a, count(b) as b from (select `col_varchar_20_key` as a, `col_double_signed` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_char_20`) as a from `table90_int_autoinc` order by a;
select count(`col_double_signed_key`) as a from `table20_int_autoinc` group by `col_decimal_6_3_unsigned` order by a;
select a, count(b) as b from (select `col_double_signed` as a, `col_decimal_10_4_unsigned` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_bigint_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_40_20_signed` order by a;
select count(distinct `col_decimal_10_4_unsigned_key`) as a from `table80_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_6_3_unsigned_key` order by a;
select count(`col_decimal_10_4_unsigned`) as a from `table70_int_autoinc` group by `col_decimal_6_3_unsigned` order by a;
select count(`col_decimal_10_4_unsigned`) as a from `table20_int_autoinc` group by `col_float_signed`, `col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table30_int_autoinc` group by `col_char_20_key` order by a;
select count(`col_float_signed`) as a from `table80_int_autoinc` group by `col_float_signed_key`, `col_bigint_signed_key` order by a;
select count(`pk`) as a from `table30_int_autoinc` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table20_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table50_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_double_signed_key` as a, `col_decimal_6_3_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(distinct b) as b from (select `col_decimal_40_20_unsigned_key` as a, `col_decimal_10_4_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_unsigned_key`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_float_signed_key`) as a from `table50_int_autoinc` order by a;
select count(`col_bigint_unsigned`) as a from `table20_int_autoinc` order by a;
select count(`col_float_signed_key`) as a from `table30_int_autoinc` order by a;
select count(distinct `col_double_signed`) as a from `table70_int_autoinc` order by a;
select a, count(distinct b) as b from (select `col_decimal_10_4_signed` as a, `col_decimal_10_4_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select a, count(b) as b from (select `pk` as a, `col_double_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_float_signed`) as a from `table50_int_autoinc` group by `col_float_signed`, `col_decimal_6_3_unsigned` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table50_int_autoinc` group by `col_char_20_key` order by a;
select count(`col_double_signed`) as a from `table90_int_autoinc` group by `col_bigint_signed` order by a;
select count(distinct `col_double_signed`) as a from `table60_int_autoinc` group by `col_float_signed` order by a;
select count(distinct `col_bigint_signed_key`) as a from `table40_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(`col_decimal_6_3_unsigned`) as a from `table10_int_autoinc` order by a;
select count(`col_decimal_10_4_signed_key`) as a from `table30_int_autoinc` group by `col_varchar_20` order by a;
select a, count(distinct b) as b from (select `col_bigint_signed` as a, `col_bigint_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_40_20_unsigned_key`) as a from `table30_int_autoinc` group by `col_decimal_40_20_signed` order by a;
select count(`col_double_signed`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_bigint_unsigned_key`) as a from `table50_int_autoinc` group by `col_bigint_signed` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from `table50_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_decimal_10_4_unsigned` order by a;
select count(`col_float_signed_key`) as a from `table40_int_autoinc` group by `col_decimal_40_20_signed`, `col_decimal_6_3_unsigned_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_40_20_signed` as a, `col_varchar_20_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_6_3_signed`) as a from `table50_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(distinct `col_decimal_6_3_unsigned`) as a from `table70_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_char_20`) as a from `table90_int_autoinc` order by a;
select count(distinct `col_bigint_unsigned`) as a from `table50_int_autoinc` group by `col_double_signed`, `pk` order by a;
select a, count(b) as b from (select `col_bigint_signed_key` as a, `col_decimal_10_4_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_double_signed`) as a from `table20_int_autoinc` group by `col_double_signed`, `col_varchar_20_key` order by a;
select a, count(b) as b from (select `col_double_signed` as a, `col_decimal_6_3_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_unsigned_key`) as a from `table80_int_autoinc` order by a;
select count(`col_varchar_20`) as a from `table80_int_autoinc` group by `col_bigint_signed_key` order by a;
select count(`col_decimal_10_4_signed`) as a from `table90_int_autoinc` group by `col_bigint_unsigned_key`, `col_decimal_6_3_signed_key` order by a;
select count(distinct `col_bigint_signed`) as a from `table10_int_autoinc` group by `col_bigint_signed_key` order by a;
select a, count(b) as b from (select `col_decimal_40_20_signed` as a, `col_decimal_6_3_unsigned` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from `table70_int_autoinc` group by `col_double_unsigned_key`, `pk` order by a;
select count(`col_decimal_10_4_unsigned_key`) as a from `table30_int_autoinc` order by a;
select count(`col_bigint_signed_key`) as a from `table20_int_autoinc` group by `col_char_20_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_signed_key` as a, `col_double_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_unsigned`) as a from `table30_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a;
select count(`col_decimal_6_3_unsigned_key`) as a from `table60_int_autoinc` group by `col_char_20` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from `table60_int_autoinc` order by a;
select count(`col_decimal_6_3_signed_key`) as a from `table60_int_autoinc` order by a;
select count(distinct `col_decimal_10_4_signed_key`) as a from `table10_int_autoinc` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table60_int_autoinc` group by `col_bigint_signed_key`, `col_decimal_10_4_unsigned` order by a;
select a, count(b) as b from (select `pk` as a, `col_decimal_40_20_unsigned_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_double_signed`) as a from `table10_int_autoinc` group by `col_decimal_6_3_unsigned_key` order by a;
select a, count(b) as b from (select `col_varchar_20` as a, `col_bigint_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_varchar_20_key`) as a from `table90_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_10_4_signed` as a, `col_decimal_40_20_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_float_unsigned_key`) as a from `table70_int_autoinc` group by `col_decimal_40_20_unsigned` order by a;
select count(distinct `col_char_20_key`) as a from `table20_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_40_20_unsigned_key` order by a;
select count(distinct `col_decimal_10_4_unsigned`) as a from `table40_int_autoinc` group by `col_decimal_40_20_signed_key`, `col_decimal_6_3_unsigned` order by a;
select count(`col_float_unsigned`) as a from `table10_int_autoinc` group by `pk`, `col_bigint_unsigned_key` order by a;
select count(`col_double_unsigned_key`) as a from `table50_int_autoinc` group by `col_bigint_unsigned_key`, `col_decimal_10_4_unsigned` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table70_int_autoinc` group by `col_varchar_20_key` order by a;
select count(distinct `col_float_signed_key`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_decimal_10_4_signed`) as a from `table70_int_autoinc` group by `col_decimal_40_20_signed`, `col_bigint_signed_key` order by a;
select a, count(distinct b) as b from (select `col_decimal_6_3_unsigned` as a, `col_decimal_10_4_unsigned_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_varchar_20`) as a from `table70_int_autoinc` group by `col_decimal_10_4_unsigned` order by a;
select count(`col_bigint_signed_key`) as a from `table50_int_autoinc` group by `col_float_signed_key`, `col_decimal_6_3_unsigned_key` order by a;
select count(`col_varchar_20_key`) as a from `table40_int_autoinc` group by `col_bigint_unsigned` order by a;
select count(distinct `col_decimal_6_3_signed_key`) as a from `table10_int_autoinc` order by a;
select count(`col_double_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a;
select a, count(distinct b) as b from (select `col_varchar_20_key` as a, `col_decimal_10_4_unsigned_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table90_int_autoinc` group by `col_decimal_40_20_signed` order by a;
select a, count(b) as b from (select `col_bigint_signed` as a, `col_varchar_20` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_10_4_signed`) as a from `table70_int_autoinc` group by `col_decimal_40_20_signed_key` order by a;
select count(distinct `col_decimal_40_20_signed`) as a from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a;
select count(`col_double_signed`) as a from `table70_int_autoinc` order by a;
select a, count(b) as b from (select `col_decimal_40_20_unsigned` as a, `col_decimal_40_20_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b;
select count(`col_decimal_40_20_unsigned`) as a from `table40_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_float_signed_key` order by a;
select count(distinct `col_float_signed`) as a from `table80_int_autoinc` group by `col_decimal_10_4_signed_key` order by a;
select count(distinct `col_decimal_40_20_unsigned_key`) as a from `table70_int_autoinc` group by `col_char_20` order by a;
select count(`col_double_unsigned_key`) as a from `table10_int_autoinc` group by `col_decimal_40_20_signed_key`, `col_decimal_40_20_signed_key` order by a;
select count(`col_decimal_40_20_signed`) as a from `table80_int_autoinc` order by a;
select count(distinct `col_decimal_6_3_unsigned_key`) as a from `table30_int_autoinc` order by a;
