select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `pk`) as b from `table40_int_autoinc` group by `col_bigint_unsigned`, `col_varchar_20_key` order by a, b;
select min(`col_float_unsigned`) as a, max(`col_decimal_6_3_unsigned_key`) as b from `table30_int_autoinc` group by `col_decimal_6_3_signed` order by a, b;
select min(`col_varchar_20`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table50_int_autoinc` group by `col_double_signed`, `col_decimal_10_4_signed` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_char_20`) as b from `table10_int_autoinc` group by `col_double_unsigned_key`, `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table60_int_autoinc` group by `col_decimal_10_4_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `pk` as a, `col_double_signed` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_unsigned_key`) as a, max(`col_decimal_6_3_signed`) as b from `table10_int_autoinc` group by `col_double_unsigned_key` order by a, b;
select min(distinct `col_decimal_6_3_unsigned`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table60_int_autoinc` group by `col_double_unsigned_key`, `col_decimal_10_4_unsigned_key` order by a, b;
select min(`col_decimal_6_3_unsigned`) as a, max(`col_bigint_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_char_20_key` as a, `col_char_20` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned` as a, `col_decimal_6_3_unsigned_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_unsigned_key`) as a, max(`col_double_unsigned`) as b from `table90_int_autoinc` group by `col_float_unsigned_key`, `col_decimal_6_3_signed_key` order by a, b;
select min(distinct `col_double_unsigned_key`) as a, max(distinct `col_double_unsigned_key`) as b from `table10_int_autoinc` group by `col_decimal_10_4_signed` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_float_signed_key`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_char_20_key`) as a, max(distinct `col_float_unsigned`) as b from `table10_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed` as a, `col_bigint_signed_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_varchar_20_key`) as a, max(distinct `col_decimal_10_4_unsigned_key`) as b from `table60_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select min(distinct `col_float_signed`) as a, max(distinct `col_decimal_6_3_signed`) as b from `table80_int_autoinc` group by `col_decimal_40_20_unsigned` order by a, b;
select min(`col_bigint_unsigned_key`) as a, max(`col_float_signed_key`) as b from `table10_int_autoinc` group by `col_bigint_unsigned`, `col_decimal_10_4_unsigned_key` order by a, b;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table80_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_double_signed_key` as a, `col_varchar_20_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table30_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_char_20` order by a, b;
select min(`col_double_unsigned_key`) as a, max(`col_decimal_40_20_signed_key`) as b from `table50_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table90_int_autoinc` group by `col_double_signed`, `col_double_unsigned_key` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table30_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned_key` as a, `col_varchar_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_unsigned`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table90_int_autoinc` group by `col_varchar_20` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_varchar_20_key`) as b from `table20_int_autoinc` order by a, b;
select min(`col_float_unsigned_key`) as a, max(`col_varchar_20`) as b from `table90_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_varchar_20_key` as a, `col_bigint_unsigned_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_bigint_unsigned_key`) as b from `table30_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_10_4_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned_key` as a, `col_decimal_6_3_unsigned_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_decimal_6_3_unsigned`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_char_20_key`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table20_int_autoinc` group by `col_decimal_6_3_unsigned_key` order by a, b;
select min(distinct `col_decimal_10_4_signed_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_float_signed`) as b from `table80_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed` as a, `col_decimal_6_3_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_signed`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table10_int_autoinc` group by `col_bigint_signed`, `col_char_20` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned_key` as a, `col_decimal_40_20_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_double_signed_key` as a, `col_decimal_40_20_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_float_signed`) as b from `table30_int_autoinc` group by `col_float_unsigned`, `col_float_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_signed_key` as a, `col_varchar_20` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_char_20_key`) as b from `table30_int_autoinc` group by `col_double_signed_key` order by a, b;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table80_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_double_unsigned_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned_key` as a, `col_double_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_signed_key`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table20_int_autoinc` group by `col_double_unsigned`, `col_decimal_6_3_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_char_20_key`) as b from `table50_int_autoinc` group by `col_varchar_20`, `col_char_20` order by a, b;
select min(`col_double_unsigned`) as a, max(`col_double_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(`col_bigint_signed_key`) as a, max(`col_varchar_20_key`) as b from `table50_int_autoinc` group by `col_double_signed` order by a, b;
select min(`col_double_signed`) as a, max(`col_bigint_unsigned`) as b from `table10_int_autoinc` group by `col_varchar_20` order by a, b;
select min(`col_char_20`) as a, max(`col_double_signed`) as b from `table10_int_autoinc` group by `col_decimal_6_3_signed_key`, `pk` order by a, b;
select min(`col_double_unsigned_key`) as a, max(`col_double_signed_key`) as b from `table40_int_autoinc` order by a, b;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed_key` as a, `col_bigint_signed` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_unsigned`) as a, max(`col_float_signed`) as b from `table70_int_autoinc` group by `col_varchar_20_key` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_decimal_40_20_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_signed`, `pk` order by a, b;
select min(distinct `col_decimal_40_20_signed_key`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table70_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_varchar_20` as a, `col_double_unsigned_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_decimal_10_4_signed_key`) as b from `table20_int_autoinc` group by `col_decimal_6_3_signed` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_bigint_unsigned`) as b from `table50_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_bigint_signed_key`) as b from `table90_int_autoinc` group by `col_float_signed_key` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_varchar_20`) as b from `table50_int_autoinc` group by `col_char_20`, `col_decimal_6_3_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `pk` as a, `col_char_20_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed_key` as a, `col_varchar_20` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_char_20_key`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table20_int_autoinc` group by `col_varchar_20_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned` as a, `col_decimal_40_20_signed` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table60_int_autoinc` group by `col_varchar_20_key`, `col_float_unsigned` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_char_20_key`) as b from `table20_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_unsigned`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table70_int_autoinc` order by a, b;
select min(distinct `col_char_20`) as a, max(distinct `col_char_20`) as b from `table20_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_signed` as a, `col_decimal_10_4_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned_key` as a, `col_decimal_6_3_signed_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table40_int_autoinc` order by a, b;
select min(`col_decimal_40_20_signed_key`) as a, max(`col_char_20`) as b from `table70_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_10_4_unsigned` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_varchar_20`) as a, max(`col_decimal_40_20_signed_key`) as b from `table30_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table90_int_autoinc` group by `col_char_20_key`, `col_varchar_20` order by a, b;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_char_20`) as a, max(distinct `col_char_20_key`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned`) as a, max(distinct `pk`) as b from `table80_int_autoinc` order by a, b;
select min(`pk`) as a, max(`col_bigint_unsigned`) as b from `table40_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_bigint_unsigned`) as b from `table60_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_40_20_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_unsigned_key`) as a, max(`col_bigint_unsigned_key`) as b from `table80_int_autoinc` group by `col_float_signed`, `col_float_signed_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_6_3_unsigned_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_char_20`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table80_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_6_3_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_float_signed_key`) as b from `table80_int_autoinc` group by `col_decimal_10_4_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `pk` as a, `col_bigint_signed_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_bigint_signed_key` as a, `col_decimal_10_4_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_double_signed`) as b from `table50_int_autoinc` group by `col_float_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned` as a, `col_decimal_10_4_unsigned` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_varchar_20_key` as a, `col_decimal_6_3_unsigned_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_signed_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table50_int_autoinc` group by `col_decimal_40_20_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_signed` as a, `col_bigint_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_bigint_signed`) as b from `table50_int_autoinc` order by a, b;
select min(`col_bigint_unsigned`) as a, max(`col_decimal_6_3_signed`) as b from `table80_int_autoinc` group by `col_float_unsigned_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_varchar_20_key`) as a, max(`col_decimal_40_20_signed_key`) as b from `table10_int_autoinc` group by `col_bigint_signed_key`, `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `col_decimal_40_20_signed_key`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_decimal_10_4_signed` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_varchar_20`) as b from `table50_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table60_int_autoinc` group by `col_double_unsigned`, `col_decimal_10_4_signed_key` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_decimal_6_3_unsigned`) as b from `table90_int_autoinc` group by `col_bigint_signed_key`, `col_decimal_40_20_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_varchar_20` as a, `pk` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_char_20`) as a, max(distinct `col_float_signed_key`) as b from `table90_int_autoinc` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_decimal_6_3_signed_key`) as b from `table20_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_decimal_6_3_unsigned_key` order by a, b;
select min(distinct `col_bigint_signed_key`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table50_int_autoinc` group by `col_char_20` order by a, b;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_decimal_10_4_unsigned_key`) as b from `table10_int_autoinc` group by `col_varchar_20_key`, `col_char_20` order by a, b;
select min(`col_decimal_10_4_unsigned_key`) as a, max(`col_decimal_6_3_signed`) as b from `table20_int_autoinc` order by a, b;
select min(`col_decimal_6_3_signed`) as a, max(`col_bigint_unsigned_key`) as b from `table80_int_autoinc` group by `col_float_unsigned` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned_key` as a, `col_varchar_20` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table40_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_signed_key` as a, `col_varchar_20_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_varchar_20`) as b from `table70_int_autoinc` group by `col_float_unsigned` order by a, b;
select min(`col_double_signed`) as a, max(`col_bigint_unsigned`) as b from `table30_int_autoinc` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table90_int_autoinc` group by `col_char_20_key`, `col_bigint_signed` order by a, b;
select min(`col_float_unsigned_key`) as a, max(`col_decimal_6_3_unsigned`) as b from `table80_int_autoinc` group by `col_double_signed_key` order by a, b;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table40_int_autoinc` group by `col_float_signed`, `col_varchar_20` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_bigint_signed_key`) as b from `table10_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table60_int_autoinc` order by a, b;
select min(`col_float_unsigned_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table50_int_autoinc` order by a, b;
select min(`col_decimal_10_4_unsigned_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table80_int_autoinc` group by `col_char_20_key`, `pk` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_unsigned_key` as a, `col_bigint_signed_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_char_20`) as b from `table40_int_autoinc` order by a, b;
select min(`pk`) as a, max(`col_char_20_key`) as b from `table20_int_autoinc` group by `col_decimal_6_3_signed`, `col_decimal_6_3_signed_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_6_3_unsigned_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_unsigned`, `pk` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_decimal_6_3_signed`) as b from `table40_int_autoinc` order by a, b;
select min(distinct `col_bigint_signed_key`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_bigint_signed_key`) as b from `table80_int_autoinc` group by `col_float_unsigned`, `col_float_unsigned` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_float_signed`) as b from `table10_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_10_4_unsigned_key` as a, `pk` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`pk`) as a, max(`col_double_signed_key`) as b from `table70_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed_key` as a, `col_double_unsigned_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table10_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_signed_key` as a, `col_bigint_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table80_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_decimal_6_3_signed` order by a, b;
select min(`pk`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table10_int_autoinc` order by a, b;
select min(distinct `pk`) as a, max(distinct `col_double_unsigned_key`) as b from `table40_int_autoinc` order by a, b;
select min(`col_varchar_20`) as a, max(`col_decimal_10_4_signed_key`) as b from `table60_int_autoinc` order by a, b;
select min(`col_bigint_signed`) as a, max(`col_float_unsigned`) as b from `table70_int_autoinc` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`pk`) as b from `table60_int_autoinc` group by `col_varchar_20` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`pk`) as b from `table30_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_float_unsigned` order by a, b;
select min(distinct `col_bigint_unsigned`) as a, max(distinct `col_bigint_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_signed_key` as a, `col_decimal_40_20_signed` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`pk`) as a, max(`col_varchar_20`) as b from `table30_int_autoinc` group by `col_float_unsigned_key`, `col_bigint_unsigned` order by a, b;
select min(`col_double_unsigned`) as a, max(`col_float_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_float_signed`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_char_20_key`) as a, max(distinct `col_double_signed`) as b from `table80_int_autoinc` group by `col_char_20` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_decimal_6_3_signed`) as b from `table30_int_autoinc` group by `col_decimal_10_4_signed_key` order by a, b;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table10_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table30_int_autoinc` group by `col_bigint_signed_key`, `col_bigint_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table70_int_autoinc` group by `col_double_signed`, `col_float_signed` order by a, b;
select min(`col_decimal_10_4_unsigned_key`) as a, max(`col_decimal_10_4_signed`) as b from `table70_int_autoinc` group by `col_decimal_10_4_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_varchar_20` as a, `col_bigint_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_signed_key`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table10_int_autoinc` group by `pk` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_bigint_unsigned_key` as a, `col_varchar_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`pk`) as a, max(`col_decimal_6_3_signed_key`) as b from `table40_int_autoinc` group by `col_bigint_signed` order by a, b;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_double_signed`) as b from `table40_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select min(`col_bigint_signed_key`) as a, max(`col_decimal_6_3_signed_key`) as b from `table50_int_autoinc` group by `col_varchar_20_key`, `col_decimal_10_4_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned_key` as a, `col_double_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_unsigned_key`) as a, max(distinct `col_decimal_6_3_signed_key`) as b from `table50_int_autoinc` order by a, b;
select min(distinct `col_bigint_unsigned`) as a, max(distinct `col_decimal_6_3_signed`) as b from `table30_int_autoinc` group by `col_char_20`, `col_varchar_20` order by a, b;
select min(`col_decimal_10_4_signed`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table90_int_autoinc` group by `col_char_20_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed` as a, `col_bigint_signed` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_char_20_key` as a, `col_bigint_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_decimal_40_20_unsigned`) as b from `table50_int_autoinc` group by `col_decimal_6_3_signed_key` order by a, b;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_decimal_6_3_signed_key`) as b from `table40_int_autoinc` group by `col_float_signed`, `col_double_signed_key` order by a, b;
select min(distinct `col_varchar_20_key`) as a, max(distinct `col_bigint_signed`) as b from `table40_int_autoinc` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_decimal_10_4_signed`) as b from `table90_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_double_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key`, `col_decimal_40_20_unsigned_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_varchar_20` as a, `col_decimal_40_20_unsigned` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_signed`) as a, max(`col_float_unsigned`) as b from `table30_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_40_20_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_bigint_signed` as a, `col_double_signed_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table70_int_autoinc` group by `col_char_20_key`, `col_bigint_signed_key` order by a, b;
select min(`col_double_unsigned`) as a, max(`col_char_20_key`) as b from `table60_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned` as a, `col_double_unsigned` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_signed_key` as a, `col_decimal_6_3_unsigned_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_signed_key` as a, `col_char_20_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_char_20_key`) as a, max(distinct `col_float_signed`) as b from `table90_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_decimal_6_3_signed_key` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table40_int_autoinc` order by a, b;
select min(distinct `col_decimal_10_4_signed_key`) as a, max(distinct `col_double_unsigned`) as b from `table10_int_autoinc` order by a, b;
select min(`col_decimal_40_20_signed_key`) as a, max(`col_decimal_6_3_unsigned_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key`, `col_decimal_6_3_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed` as a, `col_decimal_6_3_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_double_signed_key`) as b from `table30_int_autoinc` group by `col_double_signed_key` order by a, b;
select min(`col_varchar_20`) as a, max(`col_decimal_10_4_signed_key`) as b from `table30_int_autoinc` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_bigint_signed`) as b from `table80_int_autoinc` group by `pk`, `col_varchar_20_key` order by a, b;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_double_unsigned`) as b from `table40_int_autoinc` group by `col_decimal_40_20_unsigned`, `col_float_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_signed_key` as a, `col_decimal_40_20_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_double_unsigned`) as a, max(`col_decimal_6_3_signed`) as b from `table10_int_autoinc` order by a, b;
select min(distinct `col_varchar_20_key`) as a, max(distinct `col_float_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_decimal_40_20_signed` order by a, b;
select min(`col_float_unsigned`) as a, max(`col_double_signed_key`) as b from `table90_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select min(`col_float_unsigned_key`) as a, max(`col_varchar_20_key`) as b from `table20_int_autoinc` order by a, b;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_double_signed`) as b from `table20_int_autoinc` group by `col_char_20_key`, `col_bigint_unsigned` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_decimal_6_3_signed`) as b from `table50_int_autoinc` group by `col_bigint_signed_key`, `col_bigint_signed_key` order by a, b;
select min(distinct `col_float_signed_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table50_int_autoinc` group by `col_double_signed`, `col_bigint_unsigned_key` order by a, b;
select min(distinct `col_decimal_40_20_unsigned`) as a, max(distinct `col_double_unsigned_key`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table90_int_autoinc` group by `col_double_unsigned` order by a, b;
select min(distinct `col_decimal_40_20_unsigned`) as a, max(distinct `col_float_unsigned`) as b from `table50_int_autoinc` group by `col_decimal_40_20_signed` order by a, b;
select min(`col_double_unsigned`) as a, max(`col_double_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table40_int_autoinc` group by `col_decimal_40_20_signed`, `col_decimal_10_4_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_bigint_unsigned_key` as a, `col_bigint_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_decimal_10_4_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select min(distinct `col_float_signed_key`) as a, max(distinct `col_decimal_6_3_signed_key`) as b from `table40_int_autoinc` group by `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_float_signed_key`) as b from `table30_int_autoinc` group by `col_char_20` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table70_int_autoinc` group by `col_double_unsigned_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_float_unsigned_key`) as b from `table90_int_autoinc` group by `col_double_unsigned`, `col_decimal_6_3_unsigned` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_6_3_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_double_signed_key`) as b from `table70_int_autoinc` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_decimal_10_4_signed`) as b from `table40_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a, b;
select min(`col_bigint_signed`) as a, max(`col_bigint_signed`) as b from `table30_int_autoinc` group by `col_float_signed_key` order by a, b;
select min(`col_varchar_20`) as a, max(`col_bigint_unsigned`) as b from `table20_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_unsigned`) as a, max(distinct `col_double_unsigned_key`) as b from `table40_int_autoinc` group by `col_double_unsigned_key` order by a, b;
select min(`col_char_20_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table60_int_autoinc` group by `col_bigint_unsigned`, `col_varchar_20` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_double_signed`) as b from `table30_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_double_unsigned_key`) as b from `table10_int_autoinc` group by `col_float_signed_key` order by a, b;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_bigint_unsigned`) as b from `table80_int_autoinc` group by `col_decimal_6_3_unsigned`, `col_decimal_6_3_signed` order by a, b;
select min(distinct `col_char_20`) as a, max(distinct `col_bigint_signed`) as b from `table70_int_autoinc` group by `col_char_20`, `col_bigint_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_6_3_unsigned` as a, `col_decimal_40_20_unsigned_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_40_20_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_signed`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table30_int_autoinc` order by a, b;
select min(`col_double_unsigned_key`) as a, max(`col_decimal_40_20_unsigned`) as b from `table40_int_autoinc` order by a, b;
select min(`col_float_signed`) as a, max(`col_float_signed`) as b from `table20_int_autoinc` group by `col_float_signed` order by a, b;
select min(distinct `col_double_signed_key`) as a, max(distinct `col_decimal_6_3_unsigned_key`) as b from `table30_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_signed_key` as a, `col_bigint_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_double_unsigned`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned`) as a, max(distinct `col_bigint_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table40_int_autoinc` group by `col_double_unsigned_key`, `col_decimal_10_4_signed_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_unsigned_key` as a, `col_char_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_double_signed_key`) as b from `table70_int_autoinc` group by `col_float_unsigned_key`, `col_decimal_10_4_signed_key` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table60_int_autoinc` group by `col_decimal_40_20_signed_key`, `col_double_unsigned_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_char_20`) as b from `table20_int_autoinc` order by a, b;
select min(`col_bigint_unsigned`) as a, max(`col_decimal_6_3_signed_key`) as b from `table10_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a, b;
select min(`col_float_unsigned`) as a, max(`col_decimal_40_20_signed`) as b from `table60_int_autoinc` group by `col_double_unsigned` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_bigint_unsigned`) as b from `table40_int_autoinc` group by `col_float_signed` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_varchar_20_key` as a, `col_double_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_signed`) as a, max(`col_bigint_signed`) as b from `table90_int_autoinc` group by `col_float_signed`, `col_decimal_10_4_unsigned_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_bigint_signed` as a, `pk` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_bigint_signed`) as b from `table70_int_autoinc` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_varchar_20_key`) as b from `table20_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_10_4_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_char_20` as a, `col_bigint_unsigned` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_40_20_signed`) as a, max(`col_decimal_10_4_signed_key`) as b from `table10_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_double_unsigned`) as b from `table10_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed` as a, `col_bigint_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_float_signed`) as b from `table50_int_autoinc` group by `col_decimal_6_3_signed` order by a, b;
select min(distinct `col_bigint_signed`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_bigint_signed_key` order by a, b;
select min(`col_double_signed`) as a, max(`col_decimal_6_3_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_6_3_signed_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_double_signed_key`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_float_signed`) as b from `table20_int_autoinc` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_40_20_signed`) as b from `table30_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_double_unsigned_key`) as b from `table60_int_autoinc` order by a, b;
select min(`col_double_unsigned`) as a, max(`pk`) as b from `table60_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_40_20_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `pk`) as a, max(distinct `col_char_20`) as b from `table80_int_autoinc` order by a, b;
select min(`col_decimal_6_3_unsigned`) as a, max(`col_decimal_10_4_unsigned`) as b from `table40_int_autoinc` group by `col_char_20`, `col_decimal_10_4_unsigned` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_decimal_6_3_signed`) as b from `table70_int_autoinc` group by `col_varchar_20` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_decimal_6_3_unsigned_key` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_float_signed`) as b from `table20_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `pk` as a, `col_bigint_signed_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_varchar_20`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table60_int_autoinc` group by `col_decimal_40_20_unsigned`, `col_varchar_20` order by a, b;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table90_int_autoinc` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_double_unsigned_key`) as b from `table10_int_autoinc` group by `col_char_20`, `col_double_unsigned_key` order by a, b;
select min(`pk`) as a, max(`col_double_unsigned`) as b from `table70_int_autoinc` order by a, b;
select min(`col_decimal_6_3_signed`) as a, max(`col_bigint_unsigned_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select min(`col_double_signed`) as a, max(`col_decimal_6_3_unsigned_key`) as b from `table60_int_autoinc` group by `col_varchar_20_key`, `col_decimal_40_20_signed` order by a, b;
select min(`col_float_signed`) as a, max(`col_float_signed_key`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table20_int_autoinc` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table40_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select min(`pk`) as a, max(`col_decimal_6_3_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_char_20_key`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_bigint_unsigned`) as b from `table30_int_autoinc` group by `col_bigint_unsigned_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_decimal_10_4_signed`) as a, max(`col_bigint_signed`) as b from `table80_int_autoinc` group by `col_bigint_signed`, `col_decimal_40_20_unsigned` order by a, b;
select min(distinct `col_bigint_signed_key`) as a, max(distinct `col_decimal_40_20_signed`) as b from `table60_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_unsigned_key` as a, `col_bigint_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_signed` as a, `col_decimal_6_3_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_double_signed_key`) as b from `table70_int_autoinc` group by `col_double_signed_key`, `col_float_unsigned` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_double_signed`) as b from `table80_int_autoinc` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_double_unsigned`) as b from `table80_int_autoinc` group by `col_char_20` order by a, b;
select min(`col_bigint_signed`) as a, max(`col_bigint_signed_key`) as b from `table40_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_unsigned` as a, `col_double_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_float_signed_key`) as b from `table60_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_bigint_unsigned` as a, `col_decimal_6_3_signed_key` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_10_4_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_unsigned_key`) as a, max(`col_varchar_20_key`) as b from `table40_int_autoinc` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_double_signed_key`) as b from `table40_int_autoinc` group by `col_varchar_20_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_double_unsigned`) as b from `table50_int_autoinc` order by a, b;
select min(`col_decimal_6_3_signed`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table30_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned` as a, `col_varchar_20` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_bigint_unsigned_key` as a, `col_double_unsigned_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_varchar_20_key`) as a, max(`col_bigint_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_unsigned` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_6_3_signed` as a, `col_decimal_40_20_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_signed`) as a, max(`col_decimal_6_3_unsigned`) as b from `table10_int_autoinc` order by a, b;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table70_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_float_signed` as a, `col_double_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_decimal_6_3_signed_key`) as b from `table30_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_float_signed` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_decimal_40_20_signed_key`) as b from `table90_int_autoinc` order by a, b;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_double_unsigned_key`) as b from `table70_int_autoinc` group by `col_decimal_10_4_signed_key` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_double_unsigned_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_unsigned_key` order by a, b;
select min(distinct `col_double_signed_key`) as a, max(distinct `col_float_signed`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_bigint_signed_key`) as b from `table60_int_autoinc` group by `col_varchar_20`, `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `pk`) as a, max(distinct `col_float_unsigned`) as b from `table70_int_autoinc` group by `col_float_unsigned`, `col_float_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned` as a, `col_double_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed_key` as a, `col_decimal_10_4_signed` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_varchar_20_key` as a, `col_double_signed` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_char_20`) as a, max(`col_double_signed_key`) as b from `table90_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_bigint_signed_key` as a, `col_decimal_6_3_unsigned` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_char_20`) as b from `table20_int_autoinc` group by `col_double_unsigned`, `col_bigint_unsigned_key` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_varchar_20_key`) as b from `table50_int_autoinc` group by `col_decimal_10_4_unsigned_key`, `col_float_signed` order by a, b;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table90_int_autoinc` group by `col_double_unsigned`, `col_decimal_6_3_unsigned` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_float_signed`) as b from `table80_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_char_20_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned_key` as a, `col_char_20_key` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table10_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_varchar_20`) as b from `table10_int_autoinc` group by `col_decimal_40_20_unsigned`, `col_float_signed` order by a, b;
select min(distinct `col_bigint_signed_key`) as a, max(distinct `col_varchar_20`) as b from `table60_int_autoinc` order by a, b;
select min(`col_bigint_unsigned_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_decimal_6_3_unsigned_key`) as b from `table70_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_40_20_unsigned` as b from `table50_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_unsigned_key`) as a, max(distinct `col_bigint_signed`) as b from `table10_int_autoinc` group by `col_decimal_6_3_signed`, `col_double_unsigned_key` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_float_unsigned_key`) as b from `table10_int_autoinc` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_bigint_unsigned_key`) as b from `table40_int_autoinc` order by a, b;
select min(distinct `col_double_unsigned_key`) as a, max(distinct `col_double_unsigned_key`) as b from `table80_int_autoinc` group by `col_float_signed_key`, `col_bigint_signed` order by a, b;
select min(`col_bigint_unsigned`) as a, max(`col_bigint_unsigned`) as b from `table90_int_autoinc` order by a, b;
select min(`col_decimal_10_4_signed`) as a, max(`col_float_signed_key`) as b from `table60_int_autoinc` group by `col_double_signed`, `col_float_signed_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_signed` as a, `col_decimal_10_4_signed_key` as b from `table40_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `pk` as a, `col_double_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_signed`) as a, max(`col_bigint_unsigned`) as b from `table70_int_autoinc` group by `col_decimal_6_3_unsigned`, `col_float_signed_key` order by a, b;
select min(distinct `col_float_signed_key`) as a, max(distinct `col_decimal_6_3_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_double_signed` as a, `col_char_20_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_bigint_signed`) as b from `table90_int_autoinc` group by `col_float_signed_key`, `col_double_signed` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_unsigned_key` as a, `col_decimal_40_20_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_unsigned`) as a, max(`col_float_unsigned`) as b from `table20_int_autoinc` group by `col_bigint_unsigned_key`, `col_float_unsigned` order by a, b;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_varchar_20`) as b from `table10_int_autoinc` group by `col_char_20`, `col_float_signed` order by a, b;
select min(`col_double_unsigned_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table90_int_autoinc` order by a, b;
select min(`col_bigint_signed_key`) as a, max(`col_decimal_6_3_unsigned`) as b from `table80_int_autoinc` group by `col_bigint_signed`, `col_bigint_unsigned_key` order by a, b;
select min(`col_bigint_signed`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table30_int_autoinc` group by `col_decimal_40_20_signed` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_bigint_signed`) as b from `table60_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_10_4_signed_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_float_signed_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table70_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `col_varchar_20_key`) as a, max(distinct `col_decimal_40_20_unsigned`) as b from `table80_int_autoinc` order by a, b;
select min(`col_decimal_40_20_signed_key`) as a, max(`col_bigint_unsigned`) as b from `table60_int_autoinc` group by `col_decimal_40_20_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_40_20_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_char_20`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table10_int_autoinc` group by `col_float_signed`, `col_double_signed` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_bigint_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_40_20_signed_key` order by a, b;
select min(distinct `col_float_unsigned`) as a, max(distinct `col_float_signed_key`) as b from `table50_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(distinct `col_decimal_10_4_signed`) as a, max(distinct `col_double_signed`) as b from `table10_int_autoinc` group by `pk`, `col_float_signed` order by a, b;
select min(`col_decimal_6_3_unsigned`) as a, max(`col_float_signed`) as b from `table70_int_autoinc` order by a, b;
select min(`col_char_20_key`) as a, max(`col_bigint_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_6_3_signed_key` order by a, b;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_decimal_10_4_signed`) as b from `table90_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select min(distinct `col_decimal_40_20_signed_key`) as a, max(distinct `col_bigint_signed`) as b from `table10_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_signed` as a, `col_decimal_6_3_unsigned` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_bigint_signed_key`) as b from `table50_int_autoinc` group by `pk`, `col_float_unsigned_key` order by a, b;
select min(distinct `col_float_signed`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table60_int_autoinc` group by `col_float_signed`, `col_bigint_signed` order by a, b;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_double_unsigned`) as b from `table70_int_autoinc` group by `col_decimal_40_20_signed` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_signed` as a, `col_bigint_signed_key` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_bigint_unsigned` as a, `col_decimal_6_3_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_40_20_unsigned` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_6_3_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_double_unsigned_key`) as a, max(`col_decimal_6_3_unsigned_key`) as b from `table60_int_autoinc` group by `col_varchar_20` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_40_20_signed` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_double_signed`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table10_int_autoinc` group by `pk` order by a, b;
select min(`col_decimal_10_4_signed`) as a, max(`col_decimal_40_20_unsigned`) as b from `table30_int_autoinc` group by `col_char_20` order by a, b;
select min(`col_float_signed_key`) as a, max(`col_float_signed`) as b from `table80_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_40_20_unsigned_key` order by a, b;
select min(distinct `col_double_unsigned`) as a, max(distinct `col_bigint_unsigned`) as b from `table30_int_autoinc` group by `col_char_20_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_40_20_signed_key` as a, `col_decimal_6_3_unsigned_key` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_40_20_signed_key`) as a, max(`col_double_signed_key`) as b from `table30_int_autoinc` order by a, b;
select min(`col_bigint_unsigned`) as a, max(`col_decimal_40_20_unsigned`) as b from `table40_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(`col_float_signed`) as a, max(`col_varchar_20_key`) as b from `table30_int_autoinc` group by `col_decimal_40_20_unsigned_key`, `col_decimal_10_4_unsigned` order by a, b;
select min(`col_float_unsigned_key`) as a, max(`col_float_unsigned_key`) as b from `table20_int_autoinc` group by `col_float_signed_key` order by a, b;
select min(distinct `col_decimal_10_4_signed_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table60_int_autoinc` group by `col_varchar_20` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `pk` as a, `col_decimal_40_20_signed_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_unsigned`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table20_int_autoinc` order by a, b;
select min(`col_float_unsigned`) as a, max(`col_char_20`) as b from `table10_int_autoinc` group by `col_bigint_unsigned_key`, `col_varchar_20_key` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_varchar_20`) as b from `table20_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`pk`) as b from `table70_int_autoinc` group by `col_bigint_signed_key`, `col_bigint_unsigned_key` order by a, b;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_decimal_10_4_signed`) as b from `table70_int_autoinc` group by `col_varchar_20_key` order by a, b;
select min(distinct `col_float_signed_key`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table40_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `pk` as a, `col_decimal_40_20_signed` as b from `table30_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_unsigned`) as a, max(distinct `col_decimal_10_4_unsigned_key`) as b from `table80_int_autoinc` group by `col_double_unsigned`, `col_decimal_6_3_signed_key` order by a, b;
select min(distinct `col_bigint_signed_key`) as a, max(distinct `col_varchar_20_key`) as b from `table80_int_autoinc` group by `col_float_signed` order by a, b;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table60_int_autoinc` group by `col_varchar_20` order by a, b;
select min(`col_varchar_20`) as a, max(`pk`) as b from `table50_int_autoinc` group by `col_decimal_40_20_unsigned`, `col_float_signed_key` order by a, b;
select min(distinct `col_bigint_unsigned`) as a, max(distinct `col_varchar_20_key`) as b from `table40_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_decimal_6_3_signed`) as b from `table80_int_autoinc` group by `col_float_unsigned_key`, `col_decimal_40_20_signed_key` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_float_unsigned_key`) as b from `table20_int_autoinc` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table20_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_signed` as a, `col_decimal_10_4_unsigned` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed`) as a, max(distinct `col_float_signed_key`) as b from `table60_int_autoinc` group by `col_bigint_signed`, `col_varchar_20` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_decimal_10_4_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned` as a, `col_decimal_40_20_signed` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned` as a, `col_double_signed` as b from `table70_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_40_20_unsigned` as a, `col_decimal_40_20_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_char_20`) as b from `table20_int_autoinc` group by `col_float_signed_key`, `col_decimal_10_4_signed_key` order by a, b;
select min(distinct `col_char_20_key`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table10_int_autoinc` group by `col_double_signed_key` order by a, b;
select min(distinct `col_char_20`) as a, max(distinct `col_double_signed_key`) as b from `table70_int_autoinc` group by `col_float_unsigned_key`, `col_float_unsigned` order by a, b;
select min(`col_decimal_10_4_unsigned`) as a, max(`col_double_unsigned_key`) as b from `table10_int_autoinc` group by `col_decimal_40_20_signed_key` order by a, b;
select min(`col_bigint_signed`) as a, max(`col_decimal_40_20_signed`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_unsigned_key`) as a, max(distinct `col_bigint_signed`) as b from `table60_int_autoinc` order by a, b;
select min(distinct `col_varchar_20`) as a, max(distinct `col_double_unsigned`) as b from `table90_int_autoinc` group by `col_float_signed_key`, `col_float_unsigned_key` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_decimal_6_3_signed_key`) as b from `table30_int_autoinc` group by `col_decimal_10_4_unsigned`, `col_double_signed` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_double_signed`) as b from `table30_int_autoinc` order by a, b;
select min(distinct `col_bigint_signed`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table40_int_autoinc` group by `col_double_unsigned`, `col_decimal_40_20_unsigned_key` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_char_20` as a, `col_decimal_10_4_unsigned_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_char_20_key`) as a, max(`pk`) as b from `table90_int_autoinc` group by `col_bigint_unsigned_key`, `col_char_20_key` order by a, b;
select min(distinct `col_decimal_6_3_unsigned`) as a, max(distinct `col_char_20`) as b from `table10_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_float_signed` as a, `col_varchar_20` as b from `table20_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_bigint_signed`) as a, max(distinct `col_decimal_40_20_signed_key`) as b from `table10_int_autoinc` group by `col_varchar_20_key`, `col_double_unsigned_key` order by a, b;
select min(`col_decimal_40_20_unsigned_key`) as a, max(`col_decimal_6_3_signed`) as b from `table90_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_decimal_10_4_unsigned` as a, `col_varchar_20` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_40_20_signed_key`) as a, max(distinct `col_double_unsigned_key`) as b from `table90_int_autoinc` group by `col_float_signed_key`, `col_float_unsigned_key` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table60_int_autoinc` group by `col_bigint_signed_key` order by a, b;
select min(`col_decimal_10_4_signed_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table20_int_autoinc` group by `col_float_unsigned_key` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table90_int_autoinc` group by `col_bigint_signed` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_bigint_signed`) as b from `table70_int_autoinc` order by a, b;
select min(distinct `col_decimal_10_4_unsigned_key`) as a, max(distinct `col_char_20_key`) as b from `table50_int_autoinc` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_char_20_key`) as b from `table40_int_autoinc` group by `col_double_unsigned_key` order by a, b;
select min(`col_decimal_6_3_unsigned_key`) as a, max(`col_bigint_signed_key`) as b from `table40_int_autoinc` group by `pk` order by a, b;
select min(distinct `col_decimal_6_3_signed`) as a, max(distinct `col_bigint_unsigned`) as b from `table50_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_decimal_6_3_signed_key`) as b from `table70_int_autoinc` group by `col_bigint_signed_key`, `col_decimal_40_20_unsigned_key` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `pk` as a, `col_decimal_6_3_unsigned_key` as b from `table90_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_decimal_10_4_signed_key`) as a, max(distinct `col_float_signed_key`) as b from `table70_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_double_unsigned_key` as a, `col_bigint_signed` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_decimal_10_4_signed`) as a, max(`col_decimal_10_4_signed_key`) as b from `table80_int_autoinc` order by a, b;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_6_3_unsigned` as a, `col_decimal_6_3_signed_key` as b from `table60_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_double_unsigned`) as b from `table30_int_autoinc` group by `col_float_unsigned_key`, `col_bigint_signed_key` order by a, b;
select min(distinct `col_float_signed_key`) as a, max(distinct `col_bigint_unsigned_key`) as b from `table20_int_autoinc` group by `col_char_20` order by a, b;
select min(distinct `col_double_signed_key`) as a, max(distinct `pk`) as b from `table20_int_autoinc` order by a, b;
select min(`col_bigint_signed_key`) as a, max(`col_double_unsigned`) as b from `table60_int_autoinc` group by `col_decimal_10_4_signed_key`, `col_double_unsigned` order by a, b;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `pk`) as b from `table20_int_autoinc` group by `pk` order by a, b;
select min(`col_decimal_6_3_signed`) as a, max(`col_decimal_6_3_unsigned`) as b from `table80_int_autoinc` group by `col_bigint_unsigned` order by a, b;
select min(`col_decimal_40_20_unsigned`) as a, max(`col_varchar_20_key`) as b from `table40_int_autoinc` group by `col_double_signed_key`, `col_decimal_40_20_unsigned` order by a, b;
select min(`col_decimal_10_4_unsigned_key`) as a, max(`col_decimal_40_20_signed`) as b from `table80_int_autoinc` order by a, b;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_varchar_20_key`) as b from `table50_int_autoinc` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_40_20_unsigned_key`) as b from `table70_int_autoinc` group by `col_decimal_6_3_signed`, `pk` order by a, b;
select min(distinct `col_decimal_6_3_signed_key`) as a, max(distinct `col_decimal_10_4_signed_key`) as b from `table90_int_autoinc` group by `col_decimal_40_20_signed` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table80_int_autoinc` group by `col_decimal_6_3_unsigned` order by a, b;
select min(distinct `col_char_20`) as a, max(distinct `col_char_20`) as b from `table60_int_autoinc` group by `col_float_signed_key` order by a, b;
select min(`col_double_signed_key`) as a, max(`col_decimal_10_4_signed_key`) as b from `table40_int_autoinc` group by `col_decimal_40_20_unsigned` order by a, b;
select min(`col_decimal_6_3_signed`) as a, max(`col_char_20`) as b from `table20_int_autoinc` group by `col_float_signed`, `col_bigint_unsigned` order by a, b;
select min(`col_decimal_10_4_signed`) as a, max(`col_char_20_key`) as b from `table40_int_autoinc` order by a, b;
select min(`col_decimal_40_20_signed`) as a, max(`col_double_signed_key`) as b from `table50_int_autoinc` order by a, b;
select a, min(distinct tmp.b) as b, max(distinct tmp.b) as c from (select `col_char_20` as a, `col_varchar_20_key` as b from `table10_int_autoinc`) tmp group by a order by lower(a), b, c;
select a, min(tmp.b) as b, max(tmp.b) as c from (select `col_decimal_10_4_signed` as a, `col_decimal_40_20_signed_key` as b from `table80_int_autoinc`) tmp group by a order by lower(a), b, c;
select min(`col_bigint_signed`) as a, max(`col_decimal_6_3_unsigned_key`) as b from `table70_int_autoinc` order by a, b;
select min(distinct `col_float_unsigned_key`) as a, max(distinct `col_decimal_40_20_unsigned_key`) as b from `table40_int_autoinc` group by `col_bigint_unsigned`, `col_float_unsigned` order by a, b;
select min(`col_float_signed`) as a, max(`col_float_signed`) as b from `table30_int_autoinc` group by `col_varchar_20`, `col_double_signed_key` order by a, b;
select min(`col_varchar_20_key`) as a, max(`col_decimal_10_4_unsigned_key`) as b from `table80_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_char_20` order by a, b;
select min(distinct `col_float_signed`) as a, max(distinct `col_decimal_6_3_unsigned`) as b from `table80_int_autoinc` group by `col_bigint_unsigned_key` order by a, b;
select min(`col_decimal_6_3_signed_key`) as a, max(`col_decimal_6_3_signed_key`) as b from `table60_int_autoinc` group by `col_decimal_6_3_signed` order by a, b;
select min(distinct `col_double_signed_key`) as a, max(distinct `col_decimal_10_4_unsigned`) as b from `table30_int_autoinc` order by a, b;
select min(`col_bigint_unsigned`) as a, max(`col_double_signed_key`) as b from `table50_int_autoinc` group by `col_decimal_6_3_signed_key` order by a, b;
select min(distinct `col_double_signed`) as a, max(distinct `col_char_20`) as b from `table10_int_autoinc` group by `col_decimal_6_3_unsigned_key`, `col_double_unsigned` order by a, b;
select min(distinct `col_bigint_unsigned_key`) as a, max(distinct `col_double_unsigned`) as b from `table40_int_autoinc` group by `col_decimal_6_3_signed`, `col_decimal_40_20_signed` order by a, b;
select min(`pk`) as a, max(`col_varchar_20_key`) as b from `table90_int_autoinc` group by `col_decimal_10_4_signed`, `col_float_signed` order by a, b;
select min(distinct `col_char_20_key`) as a, max(distinct `col_float_signed`) as b from `table30_int_autoinc` order by a, b;
select min(distinct `col_decimal_40_20_unsigned_key`) as a, max(distinct `col_decimal_6_3_unsigned_key`) as b from `table60_int_autoinc` group by `col_varchar_20`, `col_float_signed_key` order by a, b;
